server:
  port: 8080
spring:
  application:
    name: BigDataWeb
  datasource:
    url: jdbc:mysql://192.168.133.132:3306/game_analysis?useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver


mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  type-aliases-package: com.bigdata.entity
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
